#!/bin/sh
# Xcode Cloud post-clone hook.
# The .xcodeproj is generated by xcodegen from project.yml and isn't committed.
# Re-generate it here so the cloud builder has a project to compile against.

set -euo pipefail

echo "==> Installing xcodegen via Homebrew"
brew install xcodegen

echo "==> Generating Xcode project from project.yml"
cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate

echo "==> Project regenerated successfully"
ls -la AsteraDev.xcodeproj
